// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrvwBoNyku8cPtSpQVRzpfpiGQzOukjo',
    appId: '1:225048395717:web:6666d135139ce792e2d5ac',
    messagingSenderId: '225048395717',
    projectId: 'coffee-shop-01',
    authDomain: 'coffee-shop-01.firebaseapp.com',
    storageBucket: 'coffee-shop-01.firebasestorage.app',
    measurementId: 'G-5PH2JDJZKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpa8hjxfpH84mOBnGxLLTvKg8MF-jNj_M',
    appId: '1:225048395717:android:795b85ea7fb95a38e2d5ac',
    messagingSenderId: '225048395717',
    projectId: 'coffee-shop-01',
    storageBucket: 'coffee-shop-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8ppdaRLbaJ4Q7Uzo6LOrcPCQ6t2WKu0',
    appId: '1:225048395717:ios:633777905c9d9a5ce2d5ac',
    messagingSenderId: '225048395717',
    projectId: 'coffee-shop-01',
    storageBucket: 'coffee-shop-01.firebasestorage.app',
    iosBundleId: 'com.hanan.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCu4s_jt04v2iQzDpzX8Hrwg6M3qqq49Q',
    appId: '1:1060197083289:ios:cfd97e3c2797cc5535f008',
    messagingSenderId: '1060197083289',
    projectId: 'coffeeshop-app-11',
    storageBucket: 'coffeeshop-app-11.firebasestorage.app',
    iosBundleId: 'com.hanan.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwoadc7tLq6MSsK_eCi31yOaCkWGFT6BI',
    appId: '1:1060197083289:web:0ed981f2d446fee935f008',
    messagingSenderId: '1060197083289',
    projectId: 'coffeeshop-app-11',
    authDomain: 'coffeeshop-app-11.firebaseapp.com',
    storageBucket: 'coffeeshop-app-11.firebasestorage.app',
  );

}